title: "Yesilkaya's Notes"
description: "Programming, maths, technology"
url: "https://anilyesilkaya.github.io"
baseurl: "/blog"

theme: minima
plugins:
  - jekyll-feed

minima:
  skin: classic
  date_format: "%b %-d, %Y"
